### ISSUE TITLE
메인페이지 작성업무

### ISSUE THREAD

**Issue by mrwebc** [mvcweb75/community#1]
header(공통)
section
footer(공통)

**Comment by mvcweb75** [comment]
header, footer 를 잘 만들어 주세요.
다른 팀원이 모두 공통으로 쓰는거 맞죠? #

**Comment by mrwebc** [comment]
네, 제가 이거 잘 할 수 있을까요?
자신없어요.... ㅋㅋ

**Comment by mrwebc** [comment]
그냥 테스트 해 본 거에요

**Comment by mvcweb75** [comment]
그럼 작업을 시작해 주세요
